skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
voting = "E61j5HM3hNhxHMruCHRp1M2dbuvahvdjZ4X1My15A16A"

[provider]
cluster = "Devnet"
wallet = "/home/sidkr/projects/solana-sandbox/id.json"

[scripts]
test = "cargo test"

[hooks]
