[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "Ei8zzgWDeAUC6wC2hRgYWXRpBn5d224hH4MUU4Mqr6mD"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
